spring:
    datasource:
        url: jdbc:mysql://bd-dp1.caido0azqzdz.us-east-1.rds.amazonaws.com:3306/dp1?useSSL=false
        username: admin
        password: DP1grupo2b
        driver-class-name: com.mysql.cj.jdbc.Driver

#JPA 
    jpa:
        hibernate:
            ddl-auto: create        