spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dp1?useSSL=false
        username: remote_user
        password: remote_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
            minimum-idle: 5
            idle-timeout: 10000
            max-lifetime: 1800000
    
#JPA 
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: false
            format-sql: false
            use_sql_comments: false
        generate-ddl: true

#MVC
    mvc:
        cors:
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

server:
    port: 8081
    servlet:
        context-path: /api

logging:
    level:
        org.hibernate.SQL: INFO
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        backend: INFO