spring:
    datasource:
        url: jdbc:mysql://bd-dp1.caido0azqzdz.us-east-1.rds.amazonaws.com:3306/dp1?useSSL=false
        username: admin
        password: DP1grupo2b
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
            minimum-idle: 5
            idle-timeout: 10000
            max-lifetime: 1800000
    
#JPA 
    jpa:
        hibernate:
            ddl-auto: update    
            hb2ddl.auto: update
            show-sql: true
            format-sql: true
            use_sql_comments: true
        generate-ddl: true

#MVC
    mvc:
        cors:
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

server:
    port: 8081

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        backend: INFO