name: Deploy

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no inf226.982.2b@inf226-982-2b.inf.pucp.edu.pe 'bash -s' << 'EOF'
          cd ~/dp1

          # Pull latest changes
          git pull origin main

          # Build and deploy the backend
          cd backend
          ./mvnw clean package
          sudo systemctl restart backend.service

          # Build and deploy the frontend
          cd ../frontend
          npm install
          npm run build
          pm2 restart frontend
        EOF
